import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import type { Deposit, ListDeposit } from "@/types/wallet";


const ASSETS = [
  { symbol: "BTC", name: "Bitcoin" },
  { symbol: "ETH", name: "Ethereum" },
  { symbol: "USDT", name: "Tether" },
];

function StatusBadge({ status }: { status: Deposit["status"] }) {
  if (status === "COMPLETED") {
    return <Badge className="rounded-full">completed</Badge>;
  }
  if (status === "FAILED") {
    return <Badge variant="destructive" className="rounded-full">failed</Badge>;
  }
  return <Badge variant="secondary" className="rounded-full">pending</Badge>;
}

export function WalletOverview({
  deposits,
  onOpenDeposit,
}: {
  deposits?: Deposit[];
  onOpenDeposit: (id: string) => void;
}) {
  const depositsList = Array.isArray(deposits) ? deposits : [];

  const balances = depositsList
    .filter((d) => d.status === "COMPLETED")
    .reduce((acc, d) => {
      acc[d.asset] = (Number(acc[d.asset] || 0) + Number(d.amount)).toString();
      return acc;
    }, {} as Record<string, string>);

  return (
    <div className="grid gap-4 lg:grid-cols-3">
      <Card className="rounded-2xl lg:col-span-2">
        <CardHeader>
          <CardTitle>balances</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="grid gap-3 md:grid-cols-3">
            {ASSETS.map((a) => (
              <Card key={a.symbol} className="rounded-2xl">
                <CardContent className="p-4">
                  <p className="text-sm text-muted-foreground">{a.symbol}</p>
                  <p className="text-xl font-semibold">{balances[a.symbol] || "0"}</p>
                  <p className="text-xs text-muted-foreground">{a.name}</p>
                </CardContent>
              </Card>
            ))}
          </div>

          <Separator />

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <p className="text-sm font-medium">latest deposits</p>
              <p className="text-xs text-muted-foreground">click to view details</p>
            </div>

            <div className="space-y-2">
              {depositsList.slice(0, 5).map((d) => (
                <button
                  key={d._id}
                  onClick={() => onOpenDeposit(d._id)}
                  className="w-full rounded-2xl border p-3 text-left transition hover:bg-muted/40"
                >
                  <div className="flex items-center justify-between gap-3">
                    <div className="min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="font-medium">{d.asset}</span>
                        <span className="text-xs text-muted-foreground">{d.network}</span>
                        <StatusBadge status={d.status} />
                      </div>
                      <p className="mt-1 text-xs text-muted-foreground">
                        {new Date(d.createdAt).toLocaleString()}
                      </p>
                    </div>
                    <span className="text-sm">{d.amount}</span>
                  </div>
                </button>
              ))}
              {depositsList.length === 0 && (
                <div className="rounded-2xl border p-4 text-sm text-muted-foreground">
                  no deposits yet. switch to deposit tab to create one.
                </div>
              )}
            </div>
          </div>
        </CardContent>
      </Card>

      <Card className="rounded-2xl">
        <CardHeader>
          <CardTitle>safety tips</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm text-muted-foreground">
          <p>addresses are generated by the backend</p>
          <p>network mismatch causes permanent loss</p>
          <p>confirmations update automatically</p>
          <p>tx hash appears once detected on chain</p>
        </CardContent>
      </Card>
    </div>
  );
}